### ISSUE TITLE
[Enhancement] Adding nsst.desktop

### ISSUE THREAD

**Issue by MalcolmReed-ent** [summaryInfo/nsst#1]
I've tried this terminal and found it quite nice, especially when used with dwl and emenu. However, I've encountered a minor issue when utilizing wofi to launch programs, as it requires a .desktop file. I'm curious about the feasibility of adding a desktop file.

**Comment by summaryInfo** [comment]
Thank you for the feedback!

There are now two separate desktop files: for standalone terminal windows and for the daemon mode.
No icons are provided yet though.
