### ISSUE TITLE
[Enhancement] nsstc should load configs from daemon

### ISSUE THREAD

**Issue by HalanoSiblee** [summaryInfo/nsst#4]
Each open of nsstc client it reads configs from disk which slow down startup a little bit
It should read it from the daemon process (memory) is way faster.

**Comment by summaryInfo** [comment]
Now the behavior is configurable with `--clone-config`/`clone-config=true` option. It's off by default since the config might change while the daemon is running. Thanks for the suggestion!

**Comment by summaryInfo** [comment]
Hmm, your suggestion it makes sense.
I actually did not think about that we read config file upon daemon start anyways.
I've changed the behaviour in the following way:
* Nsst daemon loads config upon the startup.
* If you create new window with nsstc, it uses that config.
* If you create new window with Ctrl-Shift-N, it uses the config from the window the hotkey was pressed.
* If you reload the config with Ctrl-Shift-X it only reloads current window config, and global config if `--config=path` options was not specified for that window.
* If you reload the config with SIGUSR1, it reloads all windows, but does not read config from default location more than once.
* Default location is either the built-in one or the one specified for daemon itself via `--config=path`

**Comment by summaryInfo** [comment]
So if you don't specify custom config paths with that option enabled, it will only read config once on startup and once every requested config reload.
Also the config can be reloaded with `Ctrl-Shift-X` for some specific window or with SIGUSR1 (e.g. `pkill -USR1 nsst`), for every window.

**Comment by HalanoSiblee** [comment]
🤍 **splendid** 🤍
now it works as intended
nice and clean commits you did, I Thanks U .
