### ISSUE TITLE
Fonts override

### ISSUE THREAD

**Issue by HalanoSiblee** [summaryInfo/nsst#5]
`font=BlexMono Nerd Font Mono-11,Twemoji-11,Inter-11`
First defined font should override the rest glyphs (what happens is the opposite)
encounter problem break some Nerd font glyphs by twemoji
![image](https://github.com/user-attachments/assets/f166633b-27f7-4aab-aa84-4373388b5c0e) < twemoji override nerd fonts
![image](https://github.com/user-attachments/assets/4f9d73f6-6deb-45f0-8caa-a09094652783) < nerd font without other fonts
 ✔   
Im really confused by this logic why I define other fonts in first place it supposed to use the right font for an empty glyphs,,

**Comment by summaryInfo** [comment]
It actually works as intended and finds the first font from left to right on the list that contains the glyph. The problem in your case is that the ✔ glyph is not a part of the **BlexMono Nerd Font**, so if you don't specify **Twemoji**, it finds some substitute font automatically, which happens to be some different font from your system (it's **DejaVu Sans** on my system). And when you specify **Twemoji** it finds the ✔ glyph in that font and it does not attempt to search for substitutes.

Automatic font substitution can be disabled with `--no-substitute-fonts`/`substitute-fonts=false` if you want that behaviour. In that case absent glyphs will be displayed as boxes.
